publish:
  image: node:18
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - package.json
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - npm publish
