name: Publish Package to npmjs
on:
  push:
    branches: [ main ]
jobs:
  check-version:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: EndBug/version-check@v2
      with:
        file-url: https://unpkg.com/@kitzen/react-native-bip39@latest/package.json
        static-checking: localIsNew
  publish:
    needs: check-version
    if: ${{ needs.check-version.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
